# Generated by Django 3.0.2 on 2020-01-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200122_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
    ]
