# Generated by Django 3.0.2 on 2020-01-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolio_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='summary',
        ),
    ]
