# Generated by Django 3.0.2 on 2020-01-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
