# Generated by Django 3.0.2 on 2020-01-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_delete_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='slug',
        ),
    ]
