# Generated by Django 3.0.2 on 2020-02-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='photographer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
